# Generated by Django 3.1.5 on 2021-02-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20210204_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(height_field='635px', upload_to='userimage/%Y/%m/%d/'),
        ),
    ]
