# Generated by Django 3.1.5 on 2021-02-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20210207_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(height_field='635', upload_to='userimage/%Y/%m/%d/'),
        ),
    ]
