# Generated by Django 3.1.5 on 2021-02-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20210207_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('news', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='newsfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('news', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
