# Generated by Django 3.1.5 on 2021-02-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_currentevents_newsfeed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='currentevents',
            new_name='currentevent',
        ),
    ]
