# Generated by Django 3.1.5 on 2021-02-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20210215_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentevent',
            old_name='news',
            new_name='event',
        ),
    ]
